first pull for adding and styling header
ivangonzalez224/Hello-world pull request #1
Opened 2023-05-30 23:00 UTC by ivangonzalez224

This is my first personal project in Module 1 in Microverse and I added the following new features.

Added a heading section html skeleton.
Added color styles to the heading.
Updated the README.md with the latest descriptions of the project.

2023-05-31 04:15 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @ivangonzalez224 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

Pull request summary
![image](https://github.com/ivangonzalez224/Hello-world/assets/78251927/e6bab6f9-9009-40ef-8acc-5e938bf3d919)

- Please try to write a descriptive PR as I can see that your PR description is not descriptive enough, 
   - Kindly add a short summary of changes introduced in the pull request. 
   - Having a descriptive PR will help any person to understand your project feature implementation detail.

Example
![pr](https://github.com/ivangonzalez224/Hello-world/assets/78251927/35d83aea-1894-44e0-b5f9-521e360b8c29)

- Nice work adding the [README](https://github.com/microverseinc/readme-template) FILE. 
  - Please personalize the content of the readme to your project.
  - All sections that begin with the `>` should be deleted
  - Kindly fix the broken LICENSE link, we should always avoid broken links in our readme for a professional repository 💪
 
![image](https://github.com/ivangonzalez224/Hello-world/assets/78251927/64eaba97-a147-43d6-91c0-71d2b76cbc97)

  - Kindly remove **template logo**. Optionally, the students can replace it with their own logo if they have one.

- To document our work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md). The commit message should be capitalized. 🤗👍

Your commits
![image](https://github.com/ivangonzalez224/Hello-world/assets/78251927/d7f9eadb-4786-4e2c-bc75-a75331345caa)

Correct ✔️ 
```
Add the main header
Add style color to the main header
```

**IMPORTANT:** As it is not easy to change commit history, please kindly correct this behavior in the future. 🤗👍

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 19:07 UTC, ivangonzalez224 commented
Hi @abdulhamiid I made the changes in the README.md file by deleting all the sections that start with >. But I noticed that I had already deleted the template logo and also the license section that contains the broken links, that is why I ask you to tell me in which part of the README.md file you see the template logo and the broken links

2023-06-01 15:33 UTC, mahbubul14 requested changes
Hi @ivangonzalez224,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ]  You have used the correct template for the `readme` but it is not updated according to the project. Please update your `README` file. 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-02 12:23 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @ivangonzalez224 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 12:23 UTC, AbelG101 commented on index.html
- [ ] Hey Ivan, I think there's been some confusion as you're making the changes on the `master` branch but since the PR you've created is for the `add-and-styling-header` branch please make sure to checkout to that branch and make the changes there. Your README on the `master` branch is looking really good you just have to copy and paste all the changes you made to the `add-and-styling-header` branch. 😉

2023-06-02 16:25 UTC, Bantealem approved these changes
Hi @ivangonzalez224, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Professional README
- [x] Descriptive PR title and summary
## Optional suggestions
- [ ] Currently, I can't see the Linters because you have a Github conflict in your PR. Please resolve this conflict. You can [find it here](https://youtu.be/dZTVLvgexgU)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 17:11 UTC, merged